#!/bin/bash

BUILD_ROOT="$(readlink -f $(dirname "$0"))/build"

build()
{
  BUILD_TYPE="$1"

  BUILD_DIR="${BUILD_ROOT}/${BUILD_TYPE}/"

  rm -rf ${BUILD_DIR}
  mkdir -p ${BUILD_DIR}
  cd ${BUILD_DIR}

  echo ${BUILD_DIR}

  cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -B$BUILD_DIR -H$BUILD_ROOT

  if [ "$?" -gt 0 ]; then
    echo -e "\n\ncmake exited with an error. Check cmake output above."
    exit 1
  fi
}

for t in debug release; do
    build $t
done

